* Chp 10 - Ethics Of IT Organizations
** What are the Key Ethical Issues for Organizations?
This chapter touches on the following ethical topics that are pertinent to organizations in the IT industry, as well as to organizations that make use of IT:

1. The use of nontraditional workers, including temporary workers, contractors, consulting firms, H-1B visa workers, and outsourced offshore workers, gives an organization more flexibility in meeting its staffing needs, often at a lower cost Ethics of IT Organizations than if the organization used traditional workers. The use of nontraditional workers also raises ethical issues for organizations. When should such nontraditional workers be employed, and how does such employment affect an organization’s ability to grow and develop its own employees? How does the use of nontraditional workers impact the wages of the organization’s own employees?
2. Whistle-blowing, as discussed in Chapter 2, is an effort to attract public attention to a negligent, illegal, unethical, abusive, or dangerous act by a company or some other organization. It is an important ethical issue for individuals and organizations. How can you safely and effectively report mis- conduct, and how should managers handle a whistle-blowing incident?
3. Green computing is a term applied to a variety of efforts directed toward the efficient design, manufacture, operation, and disposal of IT-related products, including personal computers, laptops, servers, printers, and printer supplies. Computer manufacturers and end users are faced with many questions about when and how to transition to green computing, and at what cost.
4. The electronics and information and communications technology (ICT) industry recognizes the need for a code to address ethical issues in the areas of worker safety and fairness, environmental responsibility, and business efficiency. What has been done so far, and what still needs to be done.

** Contingent Work
Contingent work is a job situation in which an individual does not have an ~explicit or implicit contract~ for long-term employment.
*** Additional Information
- The contingent workforce includes independent contractors, temporary workers hired through employment agencies, on-call or day laborers, and on-site workers whose services are provided through contract firms.
- A firm is likely to use contingent IT workers if it experiences pronounced fluctuations in its technical staffing needs.
- Typically, these workers join a team of full-time employees and other contingent workers for the life of the project and then move on to their next assignment.
- Whether they work, when they work, and how much they work depends on the company’s need for them.
*** How to obtain contingent workers?
Organizations can obtain contingent workers in one of the following two ways.
  
**** Temporary Staffing Farms
   Temporary staffing firms recruit, train, and test job seekers in a wide range of job categories and skill levels, and then assign them to clients as needed.


- Temporary employees are often used to fill in during staff vacations and illnesses,handle seasonal workloads, and help staff special projects.

- They are not considered official employees of the company, so they are not eligible for company benefits such as vacation, sick pay, and medical insurance

- Because temporary workers do not receive additional compensation through company benefits, they are often paid a higher hourly wage than full-time employees doing equivalent work.

- Temporary working arrangements sometimes appeal to people who want maximum flexibility in their work schedule as well as a variety of work experiences. Other workers take temporary work assignments only because they are unable to find more permanent work.

**** Employee Leasing
In Employee leasing, a business (called the ~subscribing firm~) transfers all or part of its workforce to another firm (called the ~leasing firm~), which handles all human-resource-related activities and costs, such as payroll, training, and the administration of employee benefits.

- Employee leasing firms operate with minimal administrative, sales, and marketing staff to keep down overall costs, and they pass the savings on to their clients.
- Employee leasing firms are subject to special regulations regarding workers’ compensation and unemployment insurance. Because the workers are technically employees of the leasing firm, they may be eligible for some company benefits through the firm.

- The subscribing firm leases these workers, but they remain employees of the leasing firm.

***** Coemployment
Employee leasing is a type of ~coemployment~ relationship, in which ~two employers~ have actual or potential legal rights and duties with respect to the same employee or group of employees.

**** Consulting Firms
Organizations can also obtain temporary IT employees by hiring a consulting firm. Consulting organizations maintain a staff of employees with a wide range of skills and experience, up to and including world-renowned industry experts; thus, these firms can often provide the exact skills and expertise that an organization requires for a ~particular project~.

Consulting firms work with their clients on engagements for which there are typically well-defined expected results or deliverables that must be produced (e.g., creation of an IT strategic plan, implementation of an enterprise resource planning [ERP] system, or selection of a hardware vendor).

The contract with a consulting firm typically specifies the length of the engagement and the rate of pay for each of the consultants, who are directed on the engagement by a senior manager or director from the consulting firm. 

*** Advantage of Using Contingent Workers
1. When a firm employs a contingent worker, it does not usually have to provide benefits such as insurance, paid time off, and contributions to a retirement plan.

2. A company can easily adjust the number of contingent workers it uses to meet its business needs, and can release contingent workers when they are no longer needed. An organization cannot usually do the same with full-time employees without creating a great deal of ill will and negatively impacting employee morale.

3. Moreover, because many contingent workers are already specialists in a particular task, a firm does not customarily incur training costs for contingent workers.

 Therefore, the use of contingent workers can enable a firm to meet its staffing needs more efficiently, lower its labor costs, and respond more quickly to changing market conditions.

*** Disadvantages of Using Contingent Workers
1. One downside to using contingent workers is that they may not feel a strong connection to the company for which they are working. This can result in a low commitment to the company and its projects, along with a high turnover rate.

2. Although contingent workers may already have the necessary technical training for a temporary job, many contingent workers gain additional skills and knowledge while working for a particular company; those assets are lost to the company when a contingent worker departs at a project’s completion.

*** Deciding when to use contingent workers
The ~trade-off~ between completing a single project quickly and cheaply versus developing people within its own organization.

1. If the project requires unique skills that are probably not necessary for future projects, there may be little reason to invest the additional time and costs required to develop those skills in full-time employees. Or,
2. if a particular project requires only temporary help that will not be needed for future projects, the use of contingent workers is a good approach.


However, organizations should carefully consider whether or not to use contingent workers when those workers are likely to learn ~corporate processes and strategies~ that are key to the company’s success. It is next to impossible to prevent contingent workers from passing on such information to subsequent employers. This can be damaging if the worker’s next employer is a major competitor.

Though using contingent workers is often the most flexible and cost-effective way to get a job done, their use can raise ~ethical and legal issues about the relationships~ among the staffing firm, its employees, and its customers—including the potential liability of a staffing firm’s customers for withholding payroll taxes, payment of employee retirement benefits and health insurance premiums, and administration of workers’ compensation to the staffing firm’s employees.

Additionally, Depending on how closely workers are ~supervised and how the job is structured~, contingent workers may be viewed as permanent employees by the Internal Revenue Service, the Department of Labor, or a state’s workers’ compensation and unemployment agencies.

** H-1B Worker
An H-1B visa is a temporary work visa granted by the  (USCIS) for people who work in specialty occupations—jobs that require at least a four-year bachelor’s degree in a specific field, or equivalent experience.

USCIS = U.S. Citizenship and Immigration Services

A person can work for a U.S. employer as an H-1B employee for a maximum continuous period of six years.

Considerations:
- English Skills
- Innovation & Entrepreneurship
- Heavy reliance on the use of H-1B workers can lessen the incentive for U.S. companies to educate and develop their own workforces.

Potenial Expoitation:
- Low Wage
- Fraud

*** Details
When considering the use of H-1B visa workers, companies should take into account that even highly skilled and experienced H-1B workers may require help with their ~English skills~.


The researchers also concluded that “there is substantial evidence that H-1B admissions appear to directly improve levels of innovation and entrepreneurship, which in the long term should create new jobs and raise demand for technology workers in other areas."

**** Using H-1B Workers Instead of U.S. Workers
In order to compete in the global economy, U.S. firms must be able to attract the best and brightest workers from all over the world. Most H-1B workers are brought to the United States to fill a legitimate gap that cannot be filled from the existing pool of workers.

However, there are some managers who reason that as long as skilled foreign workers can be found to fill critical positions, ~why invest thousands of dollars and months of training to develop their current U.S. workers?~ Heavy reliance on the use of H-1B workers can lessen the incentive for U.S. companies to educate and develop their own workforces.

** Outsourcing
Outsourcing is a long-term business arrangement in which a company contracts for services with an ~outside organization~ that has expertise in providing a specific function.

- Coemployment legal issues are minimal.
- Speeding up project schedeule.

Offshore outsourcing is a form of outsourcing in which the services are provided by an organization whose employees are in a ~foreign country.~
- Low-cost foreign countries

Organizations must consider many factors when deciding where to locate outsourcing activities.
- Political Unrest in foreign country
- Global Services Location Index

Pros And Cons of Offshore Outsourcing:
1. 24 hour workday
2. Lower cost
3. It takes years of ongoing effort and a large upfront investment to develop a good relationship with an offshore outsourcing firm.
4. Finding a reputable vendor can be difficult for medium or small firms that lack experience in identifying and vetting contractors.
5. The trade-offs between using offshore outsourcing firms and devoting money and time to retain and develop their own staff
6. A company loses the knowledge and experience gained by outsourced workers when those workers are reassigned after a project’s completion.
7. Cultural and language differences
8. The compromising of customer data

*** Details
Coemployment legal problems with outsourcing are minimal, because the company that contracts for the services does not generally supervise or control the contractor’s employees. The primary rationale for outsourcing is to lower costs, but companies also use it to obtain strategic flexibility and to keep their staff focused on the company’s core competencies.
**** Offshore Outsourcing
Offshore outsourcing is a form of outsourcing in which the services are provided by an organization whose employees are in a ~foreign country.~

1. Any work done at a relatively high cost in the United States may become a candidate for offshore outsourcing—not just IT work. However, IT professionals in particular can do much of their work anywhere.

As more businesses move their key processes offshore, U.S. IT service providers are forced to lower prices. Many U.S. software firms set up development centers in low-cost foreign countries where they have access to a large pool of well-trained candidates

Organizations must consider many factors when deciding where to locate outsourcing
activities.
- Political Unrest in foreign country
- Global Services Location Index

***** Pros of Offshore Outsouring
- Wages that an American worker might consider low represent an excellent salary in many
other parts of the world, and some companies feel they would be foolish not to exploit such
an opportunity. Why pay a U.S. IT worker a six-figure salary, they reason, when they can
use offshore outsourcing to hire three India-based workers for the same cost? However, this
attitude might represent a short-term point of view—offshore demand is driving up salaries
in India by roughly 15 percent per year. Because of this, Indian offshore suppliers have
begun to charge more for their services. The cost advantage for offshore outsourcing to India
used to be 6:1 or more—you could hire six Indian IT workers for the cost of one U.S. IT
worker. The cost advantage is shrinking, and once it reaches about 1.5:1, the cost savings
will no longer be much of an incentive for U.S. offshore outsourcing to India.

- “24-hour workday”
- 
***** Cons of Offshore Outsourcing
In addition, organizations often find it takes years of ongoing effort and a large up-front investment to develop a good working relationship with an offshore outsourcing firm. Finding a reputable vendor can be especially difficult for a small or midsized firm that lacks experience in identifying and vetting contractors


The trade-offs between using offshore outsourcing firms and devoting money and time to retain and develop their own staff

Another downside to offshore outsourcing is that a company loses the knowledge and experience gained by outsourced workers when those workers are reassigned after a project’s completion.

Cultural and language differences

The compromising of customer data
** Strategies for successful offshore outsouring
The following list provides several tips for companies that are considering offshore
outsourcing:

1. Set clear, firm business specifications for the work to be done.
2. Assess the probability of political upheavals or factors that might interfere with information flow, and ensure the risks are acceptable.
3. Assess the basic stability and economic soundness of the outsourcing vendor and what might occur if the vendor encounters a severe financial downturn.
4. Establish reliable satellite or broadband communications between your site and the outsourcer’s location.
5. Implement a formal version-control process, coordinated through a quality assurance person.
5. Develop and use a dictionary of terms to encourage a common understanding of technical jargon.
7. Require vendors to have project managers at the client site to overcome cultural barriers and facilitate communication with offshore programmers.
8. Require a network manager at the vendor site to coordinate the logistics of using several communications providers around the world.
9. Agree in advance on the structure and content of documentation to ensure that manuals explain how the system was built, as well as how to maintain it.
10. Carefully review a current copy of the outsourcing firm’s SAS No. 70 audit report to ascertain its level of control over information technology and related processes.
** Whitle-blowing
whistle-blowing is an effort to attract public attention to a negligent, illegal, unethical, abusive, or dangerous act by a company or some other organization.

In some cases, whistle-blowers are employees who act as informants on their company, revealing information to enrich themselves or to gain revenge for a perceived wrong. In most cases, however, whistle-blowers act ethically in an attempt to correct what they think is a major wrongdoing, often at great personal risk.
*** Protection of Whistle-blowers
Unfortunately, no comprehensive federal law protects all whistle-blowers from retaliatory acts. Instead, numerous laws protect a certain class of specific whistle-blowing acts in various
industries. To make things even more complicated, each law has different filing provisions, administrative and judicial remedies, and statutes of limitations (which set time limits for
legal action)

From the whistle-blower’s perspective, a short statute of limitations is a major weakness of many whistle-blower protection laws. Failure to comply with the statute of limitations is a favorite defense of firms accused of wrongdoing in whistle-blower case

The ~qui tam~ (“who sues on behalf of the king as well as for himself”) provision of the False Claims Act allows a private citizen to file a suit in the name of the U.S. government, charging fraud by government contractors and other entities who receive or use govern- ment funds. In qui tam actions, the government has the right to intervene and join the legal proceedings. If the government declines, the private plaintiff may proceed alone. Some states have passed similar laws concerning fraud in state government contracts.

The ~False Claims Act~ provides strong whistle-blower protection. Any person who is discharged, demoted, harassed, or otherwise discriminated against because of lawful acts of whistle-blowing is entitled to all relief necessary “to make the employee whole.” Such relief may include job reinstatement; double back pay; and compensation for any special damages, including litigation costs and reasonable attorney’s fees.36
*** Whistle-blowing in private sectors
Under state law, an employee could traditionally be terminated for any reason, or no rea-
son, in the absence of an employment contract. However, many states have created laws
that prevent workers from being fired because of an employee’s participation in “pro-
tected” activities

*** Dealing with a whistleblowing situation
This section provides a general sequence of events, and highlights key issues that a potential whistle-blower should consider.
1. Assess the Seriousness of the Situation
2. Begin Documentation
3. Attempt to Address the Situation Internally
4. Consider Escalating the Situation Within the Company
5. Assess the Implications of Becoming a Whistle-Blower: blow the whistle on the company.
6. Use Experienced Resources to Develop an Action Plan
7. Execute the Action Plan
8. Live with the Consequences
** Green Computing
Green computing, also known as green technology, is the use of computers and other computing devices and equipment in energy-efficient and eco-friendly ways.
- Use less electricity
- Less carbon footprint
- Reduce the amount of hazardous materials used to produce hardwares
- Increase the amount of ~recyclable~ materials in its manufacturing and packaging process.
- The manufacturers must also help consumers dispose of their products in an environmentally safe manner at the end of their useful life.
  
EPEAT (Electronic Product Environmental Assessment Tool) is a system that enables purchasers to evaluate, compare, and select electronic products based on 51 environmental criteria.
** ICT INDUSTRY CODE OF CONDUCT
The Electronic Industry Citizenship Coalition (EICC) was established to promote a common code of conduct for the electronics and ICT industry. The following are the five areas of social responsi-
bility and guiding principles covered by the code.
*** Labor
“Participants are committed to uphold the human rights of workers, and to treat them with dignity and respect as understood by the international community.”

*** Health and Safety
“Participants recognize that in addition to minimizing the incidence of work-related injury and illness, a safe and healthy work environment enhances the quality of products and services, consistency of production and worker retention and morale. Participants also recognize that
ongoing worker input and education is essential to identifying and solving health and safety issues in the workplace.”

*** Environmental
“Participants recognize that environmental responsibility is integral to producing world class products. In manufacturing operations, adverse effects on the community, environment, and natural resources are to be minimized while safeguarding the health and safety of the public.”
*** Management System
“Participants shall adopt or establish a management system whose scope is related to the content of this Code. The management system shall be designed to ensure (a) compliance with applicable laws, regulations and customer requirements related to the participant’s operations and products; (b) conformance with this Code; and (c) identification and mitigation of operational risks related to this Code. It should also facilitate continual improvement.”
*** Ethics
“To meet social responsibilities and to achieve success in the mar- ketplace, participants and their agents are to uphold the highest standards of ethics including: business integrity; no improper advantage; disclosure of information; intellectual property; fair business, advertising, and competition; protection of identity; responsible sourcing of minerals; and privacy.”
* Chp 6 - Intellectual Property
Intellectual property is a term used to describe works of the mind—such as art, books, films, formulas, inventions, music, and processes—that are distinct and owned or created by a single person or group.

Copyright law protects authored works, such as art, books, film, and music.

Defining and controlling the appropriate level of access to intellectual property are
complex tasks. For example, protecting computer software has proven to be difficult because
it has not been well categorized under the law. Software has sometimes been treated as the
expression of an idea, which can be protected under copyright law. In other cases, software
has been treated as a process for changing a computer’s internal structure, making it eligible
for protection under patent law. At one time, software was even judged to be a series of
mental steps, making it inappropriate for ownership and ineligible for any form of protectio
** Copyright
A copyright is the exclusive right to distribute, display, perform, or reproduce an
original work in copies or to prepare derivative works based on the work. Copyright
protection is granted to the creators of “original works of authorship in any tangible
medium of expression, now known or later developed, from which they can be perceived,
reproduced, or otherwise communicated, either directly or with the aid of a machine or
device.

Copyright infringement is a violation of the rights secured by the owner of a copyright.
Infringement occurs when someone copies a substantial and material part of another’s
copyrighted work without permission. The courts have a wide range of discretion in award-
ing damages—from $200 for innocent infringement to $100,000 for willful infringement.


The types of work that can be copyrighted include architecture, art, audiovisual works,
choreography, drama, graphics, literature, motion pictures, music, pantomimes, pictures,
sculptures, sound recordings, and other intellectual works, as described in Title 17 of the
U.S. Code. To be eligible for a copyright, a work must fall within one of the preceding
categories, and it must be original.

However, evaluating the originality of a work is not always a straight-
forward process, and disagreements over whether or not a work is original sometimes lead
to litigation

Some works are not eligible for copyright protection, including those that have not
been fixed in a tangible form of expression (such as an improvisational speech) and those
that consist entirely of common information that contains no original authorship, such as
a chart showing conversions between European and American units of measure.
** Software Copyright Protection Laws
*** The Prioritizing Resources and Organization for Intellectual Property (PRO-IP) Act of 2008
This act increased trademark and copyright enforcement and substantially increased penalties for infringement. The law also created the Office of the United States Intellectual Property Enforcement Representative within the U.S. Department of Justice. One of its programs, called CHIP (Computer Hacking and Intellectual Property), is a network of over 150 experienced and specially trained federal prosecutors who focus on computer and intellectual property crimes.
*** General Agreement on Tariffs and Trade (GATT)
The General Agreement on Tariffs and Trade (GATT) was a multilateral agreement
governing international trade.

It includes a section covering copyrights called the Agreement on Trade-Related Aspects of
Intellectual Property Rights (TRIPS), discussed in the following section.

Despite GATT, however, copyright protection varies greatly from country to country, and an expert should be consulted when considering international usage of any intellectual property.
*** The WTO and the WTO TRIPS Agreement (1994)
The World Trade Organization (WTO) is a global organization that deals with rules of international trade based on WTO agreements that are negotiated and signed by representatives of the world’s trading nations.

Many nations recognize that intellectual property has become increasingly important in world trade, yet the extent of protection and enforcement of intellectual property rights varies around the world. As a result, the WTO developed the Agreement on Trade-Related Aspects of Intellectual Property Rights, also known as the TRIPS Agreement, to establish minimum levels of protection that each government must provide to the intellectual property of all WTO members.
*** The World Intellectual Property Organization (WIPO) Copyright Treaty (1996
The World Intellectual Property Organization (WIPO), headquartered in Geneva, Switzerland, is an agency of the United Nations established in 1967. WIPO is dedicated to “the use of intellectual property as a means to stimulate innovation and creativity.” It has 185 member nations and administers 25 international treaties. Since the 1990s, WIPO has strongly advocated for the interests of intellectual property owners. Its goal is to ensure that intellectual property laws are uniformly administered.
*** The Digital Millennium Copyright Act (1998)
The Digital Millennium Copyright Act (DMCA) was signed into law in 1998 and implements two 1996 WIPO treaties: the WIPO Copyright Treaty and the WIPO Performances and Phonograms Treaty. The act is divided into the following five sections:
**** Title I (WIPO Copyright and Performances and Phonograms Treaties Implementation Act of 1998)
This section implements the WIPO treaties by making certain technical amendments to U.S. law in order to provide appropriate references and links to the treaties. It also creates two new prohibitions in the Copyright Act (Title 17 of the U.S. Code)—one on circumvention of technological measures used by copyright owners to protect their works and one on tampering with copyright management information. Title I also adds civil remedies and criminal penalties for violating the prohibitions.
**** Title II (Online Copyright Infringement Liability Limitation Act)
This section enables Web site operators that allow users to post content on their Web site (e.g., music, video, and pictures) to avoid copyright infringement liability if certain “safe harbor” provisions are followed.
**** Title III (Computer Maintenance Competition Assurance Act)
This section permits the owner or lessee of a computer to make or authorize the making of a copy of a computer program in the course of maintaining or repairing that computer. The new copy cannot be used in any other manner and must be destroyed immediately after the maintenance or repair is completed.
**** Title IV (Miscellaneous provisions)
This section adds language to the Copyright Act confirming the Copyright Office’s authority to continue to per- form the policy and international functions that it has carried out for decades
under its existing general authority.
**** Title V (Vessel Hull Design Protection Act)
This section creates a new form of protection for the original design of vessel hulls.
** Patent
A patent is a grant of a property right issued by the United States Patent and Trademark Office (USPTO) to an inventor.

A patent permits its owner to exclude the public from making, using, or selling a protected invention, and it allows for legal action against violators. 

Unlike a copyright, a patent prevents independent creation as well as copying. Even if someone else invents the same item independently and with no prior knowledge of the patent holder’s invention, the second inventor is excluded from using the patented device without permission of the original patent holder.

A software patent claims as its invention some feature or process embodied in instructions executed by a computer.

~Patent infringement~, or the violation of the rights secured by the owner of a patent, occurs when someone makes unauthorized use of another’s patent. Unlike copyright infringement, there is no specified limit to the monetary penalty if patent infringement is found. In fact, if a court determines that the infringement is intentional, it can award up to three times the amount of the damages claimed by the patent holder. The most common defense against patent infringement is a counterattack on the claim of infringement and the validity of the patent itself. Even if the patent is valid, the plaintiff must still prove that every element of a claim was infringed and that the infringement caused some sort of damage.
** Cross-Licensing Agreements
Many large software companies have cross-licensing agreements in which each party agrees not to sue the other over patent infringement.

Major IT firms usually have little interest in cross-licensing with smaller firms. As a result, small businesses must pay an additional cost from which many larger companies are exempt. Furthermore, small businesses are generally unsuccessful in enforcing their patents against larger companies. Should a small business bring a patent infringement suit against a large firm, the larger firm can overwhelm the small business with multiple patent suits, whether they have merit or not.
** Trade Secret
A trade secret was defined as business information that represents something of economic value, has required effort or cost to develop, has some degree of uniqueness or novelty, is generally unknown to the public, and is kept confidential.

Trade secret protection begins by identifying all the information that must be protected—from undisclosed patent applications to market research and business plans and developing a comprehensive strategy for keeping the information secure. 

Trade secret law protects only against the misappropriation of trade secrets. If competitors come up with the same idea on their own, it is not misappropriation; in other words, the law doesn’t prevent someone from using the same idea if it was developed independently.
*** Employee & Trade Secrets
Employees are the greatest threat to the loss of company trade secrets—they might accidentally disclose trade secrets or steal them for monetary gain.

1. Organizations must ~educate~ employees about the importance of maintaining the secrecy of corporate information.
2. Trade secret information should be labeled clearly as confidential and should only be accessible by a limited number of people.
3. Most organizations have strict policies regarding ~nondisclosure~ of corporate information.
4. Because organizations can risk losing trade secrets when ~key employees leave~, they often try to prohibit employees from revealing secrets by adding nondisclosure clauses to employment contracts. Thus, departing employees ~cannot take copies of computer programs or reveal the details of software owned by the firm.~
5. Another option for preserving trade secrets is to have an ~experienced member of the Human Resources Department~ conduct an exit interview with each departing employee. A key step in the interview is to review a checklist that deals with confidentiality issues. At the end of the interview, the departing employee is asked to sign an acknowledgment of responsibility not to divulge any trade secrets.
*** Steps to protect trade secret
1. Human resources involved should have sufficient knowledge to understand what is trade secret and waht is not.
2. Involved personnel should alert the involved in thread circumstances. That is immediate decision.
3. Internal policy should be well-communicated.
4. Using non-disclosure or acknowledgement to not divulge trade secret at employee departure.
** Trade Secret Laws
*** Uniform Trade Secrets Act (UTSA)
The Uniform Trade Secrets Act (UTSA) was drafted in the 1970s to bring uniformity to all the United States in the area of trade secret law.
*** The Economic Espionage Act (EEA) (1996)
The Economic Espionage Act (EEA) of 1996 imposes penalties of up to $10 million and 15 years in prison for the theft of trade secrets. Before the EEA, there was no specific criminal statute to help pursue economic espionage;

Espionage is the activity of finding out the political, military, or industrial secrets of your enemies or rivals by using spies. 
** KEY INTELLECTUAL PROPERTY ISSUES
This section discusses several issues that apply to intellectual property and information technology.
*** Plagiarism
Plagiarism is the act of stealing someone’s ideas or words and passing them off as one’s own. The explosion of electronic content and the growth of the Web have made it easy to cut and paste paragraphs into term papers and other documents without proper citation or quotation marks.

Educate people on citations.
*** Reverse Engineering
Reverse engineering is the process of taking something apart in order to understand it, build a copy of it, or improve it. Reverse engineering was originally applied to computer hardware but is now commonly applied to software as well.
The use of reverse engineering, saying it can uncover software designs that someone else has developed at great cost and taken care to protect. Opponents of reverse engineering contend it unfairly robs the creator of future earnings and significantly reduces the business incentive for software development.
*** Open Source Code
Open source code is any program whose source code is made available for use or modification, as users or other developers see fit. The basic premise behind open source code is that when many programmers can read, redistribute, and modify a program’s code, the software improves.

A software developer could attempt to make a program open source simply by putting it into the public domain with no copyright. This would allow people to share the program and their improvements, but it would also allow others to revise the original code and then distribute the resulting software as their own proprietary product. Users who received the program in the modified form would no longer have the free- doms associated with the original software. Use of an open source license avoids this scenario.
*** Competitive Intelligence
Competitive intelligence (as defined in Chapter 3) is legally obtained information that is gathered to help a company gain an advantage over its rivals. For example, some companies have employees who monitor the public announcements of property transfers to detect any plant or store expansions of competitors. An effective competitive intelligence program requires the continual gathering, analysis, and evaluation of data with controlled dissemination of useful information to decision makers.

Competitive intelligence is not the same as industrial espionage, which is the use of illegal means to obtain business information not available to the general public.

Competitive intelligence analysts must avoid unethical or illegal actions, such as lying,
misrepresentation, theft, bribery, or eavesdropping with illegal devices.
*** Trademark Infringement
A trademark is a logo, package design, phrase, sound, or word that enables a consumer to differentiate one company’s products from another’s
*** Cybersquatting
Companies that want to establish an online presence know that the best way to capitalize on the strengths of their brand names and trademarks is to make the names part of the domain names for their Web sites. When Web sites were first established, there was no procedure for validating the legitimacy of requests for Web site names.

The main tactic organizations use to circumvent cybersquatting is to protect a trademark by registering numerous domain names and variations as soon as the organization knows it wants to develop a Web presence.
* Chp 3 - Computer & Internet Crime
** Why Computer Incidents Are So Prevalent?
1. Increasing Complexity Increases Vulnerability
2. Higher Computer User Expectations
3. Expanding and Changing Systems Introduce New Risks
4. Bring Your Own Device
5. Increased Reliance on Commercial Software with Known Vulnerabilities
** Prevention
AST MUN
1. Conduct vulnerability ~assessment~!
2. Strong security measures: IDS, access control
3. Train employees on security best practices
4. Monitor network activity
5. Up-to-date softwares
6. Use network segmentation
* Chp 2 - forgot name
[[https://docs.google.com/document/d/1TBkps7-DH7TuaZY-rTWYsV1zgnPnBVwf8500eHXIdLg/edit?usp=sharing][Source]]
** What is professionalism? Are IT Workers Professional?
Professionalism: A profession is a calling that requires specialized knowledge and often long intensive academic preparation.

IT workers require intensive training, continuous learning with changing techstacks and a key role is in their experience. And so IT Workers are also professionals.

Many business workers have ~duties, backgrounds, and training~ that qualify them to be classified as professionals, including marketing analysts, financial consultants, and IT specialists such as mobile application developers, software engineers, systems analysts, and network administrators.

One could argue, however, that not every IT role requires ~“knowledge of an advanced type in a field of science or learning customarily acquired by a prolonged course of specialized intellectual instruction and study,”~ to quote again from the United States Code. From a legal perspective, IT workers are not recognized as professionals because they are not licensed by the state or federal government. This distinction is important, for example, in malpractice lawsuits, as many courts have ruled that IT workers are not liable for malpractice because they do not meet the legal definition of a professional.
** Relationship between IT workers and client
IT workers provide services to clients; sometimes those “clients” are coworkers who are part of the same organization as the IT worker. In other cases, the client is part of a different organization.

Typically, the client makes decisions about a project on the basis of information, alternatives, and recommendations provided by the IT worker. The client trusts the IT worker to use his or her expertise and to act in the client’s best interests. The IT worker must trust that the client will provide relevant information, listen to and understand what the IT worker says, ask questions to understand the impact of key decisions, and use the information to make wise choices among various alternatives. Thus, the responsibility for decision making is shared between client and IT workers.

*** Potential Issues
- Conflict of Interest
- Schedeule issues: Problems can also arise during a project if IT workers find themselves unable to provide full and accurate reporting of the project’s status due to a lack of information, tools, or experience needed to perform an accurate assessment. The project manager may want to keep resources flowing into the project and hope that problems can be corrected before anyone notices. The project manager may also be reluctant to share status information because of contractual penalties for failure to meet the schedule or to develop certain sys- tem functions. In such a situation, the client may not be informed about a problem until it has become a crisis.
- Fraud
- Misrepresentation
- Breach of contract
** Relationships Between IT Workers and Suppliers
IT workers deal with many different hardware, software, and service providers. Most IT workers understand that building a good working relationship with suppliers encourages the flow of useful communication as well as the sharing of ideas. Such information can lead to innovative and cost-effective ways of using the supplier’s products and services that the IT worker may never have considered.
IT workers can develop good relationships with suppliers by dealing fairly with them and not making unreasonable demands. Threatening to replace a supplier who can’t deliver needed equipment tomorrow, when the normal industry lead time is one week, is aggressive behavior that does not help build a good working relationship.

Potential Issues:
- Bribery
** Relationships Between IT Workers and Other Professionals
Professionals often feel a degree of loyalty to the other members of their profession. As a result, they are often quick to help each other obtain new positions but slow to criticize each other in public.

- Resume Inflation
- Preferential Treatment
** Relationships between IT Workers and IT Users
IT workers also have a key responsibility to establish an environment that supports ethical behavior by users. Such an environment discourages 
- software piracy
- minimizes the inappropriate use of corporate computing resources
- avoids the inappropriate sharing of information
** Relationships Between IT Workers and Society
Societyy expects members of a profession to provide significant benefits and to not cause harm
through their actions. One approach to meeting this expectation is to establish and maintain professional standards that protect the public.
** Certification
Certification indicates that a professional possesses a particular set of skills, knowledge, or abilities, in the opinion of the certifying organization.
Is certification relevant to your current job or the one to which you aspire? Does the company offering the certification have a good reputation? What is the current and potential future demand for skills in this area of certification?
*** Vendor Certifications
Many IT vendors—such as Cisco, IBM, Microsoft, SAP, and Oracle—offer certification programs for those who use their products.
*** Industry Association Certifications
There are many available industry certifications in a variety of IT-related subject areas. Their value varies greatly depending on where people are in their career path, what other certifications they possess, and the nature of the IT job market.

CompTIA A+, Red Hat Linux Certification
** Compliance
Compliance means to be in accordance with established policies, guidelines, specifications, or legislation.

- Audit Committee
- Internal Audit Department
** What is professionalism? Are IT Workers professional?
Professionalism: A profession is a calling that requires specialized knowledge and often long intensive academic preparation.

IT workers require intensive training, continuous learning with changing techstacks and a key role is in their experience. And so IT Workers are also professionals.
** Issues in Employer Relationships/ Relationship between IT Worker & Professional
The employer and IT worker have a critical and multifaceted relationship that requires ongoing efforts by both parties to keep it strong. An IT worker and an employer typically agree on fundamental aspects of these relationships before the IT worker accepts an employment offer.
 
There are some issues in the employer relationship. These issues may include: Job Title, General performance expectations, specific work responsibilities, drug testing, dress code, location of employment, salary, work hour & company benefits. Some aspects are specific to the role of IT workers and are estimated based on the nature of the work or project. For example, the programming language to be used, the type and amount of documentation to be produced and the extent of testing to be conducted.

Memorize:
Job Title
specific work responsibilities
salary
work hour
General performance expectations
company benefits.
drug testing
dress code
location of employment
*** Trade Secret
IT workers should not divulge company secrets. A secret can be SRS, software design, source code, vulnerability testing report etc. 
*** Software Business Alliance
The Business Software Alliance (BSA) is a trade group that represents the world’s largest software and hardware manufacturers. Its mission is to stop the unauthorized copying of software produced by its members. 
*** Whistleblowers
Whistle-blowing is an effort by an employee to attract attention to a negligent, illegal, unethical, abusive, or dangerous act by a company that threatens the public interest
** Professional Relationships that must be maintained
Software engineering is a people intensive industry so maintaining good relationships is necessary.

** What is a professional code of ethics? Discuss about its 4 fundamental principles.
A professional code of ethics states the principles and core values that are essential to the work of a particular occupational group. Practitioners in many professions subscribe to a code of ethics that governs their behavior.

There are 4 fundamental principles of professional code of ethics. They are:
1. Ethical decision making
2. High standard of practice and ethical behavior
3. Trust and respect from the general public
4. Evaluation Benchmark
** What are IT Professional Organizations? List some of the organizations and their roles.
These organizations disseminate information through email, periodicals, Web sites, meetings, and conferences. Furthermore, in recognition of the need for professional standards of competence and conduct, many of these organizations have developed codes of ethics.

*** Association for Computing Machinery (ACM): 
- publishes over 50 journals and magazines and 30 newsletters
- offers a substantial digital library of bibliographic information, citations, articles, and journals
- 37 special-interest groups (SIGs) representing major areas of computing
*** Institute of Electrical and Electronics Engineers Computer Society (IEEE-CS):
- covers the broad fields of electrical, electronic, and information technologies and science. 
- helps meet the information and career development needs of computing researchers and practitioners with technical journals, magazines, books, conferences, conference publications, and online courses.
- offers a Certified Software Development Professional (CSDP) program for experienced professionals and a Certified Software Development Associate(CSDA) credential for recent college graduates
- Sponsors conferences
*** Association of Information Technology Professionals (AITP):
- provides IT-related seminars and conferences, information on IT issues, and forums for networking with other IT workers.
- mission is to provide superior leadership and education in information technology
help members make themselves more marketable within their industry
-  Has a code of ethics and standards of conducts
*** SysAdmin, Audit, Network, Security (SANS) Institute:
- train some 12,000 people,
- a weekly security vulnerability digest
- provides information security certification
** Common Ethical Issues of IT Users(Page 61)
Some of the common ethical Issues of IT users are:
- Software Piracy
- Inappropriate Use of Computing Resources
- Inappropriate Sharing of Information

** Supporting the Ethical Practices of IT Users 
As the concerns regarding IT professionals' code of conduct rises, companies have begun adopting policies and methodologies to support ethical practices of IT users.
- Defining the Appropriate Use of IT Resources
- Establishing guidelines for Use of Company Software
- Structuring Information Systems to Protect Data and Information
- Installing and Maintaining a Corporate Firewall
Memorize: DESI

* Chp 7 - Software Development
[[https://docs.google.com/document/d/1HFdy68xJJUp1OHd-5r7oob6gQZFAFt_rcoKgP89fubE/edit?usp=sharing][source]]
** Definition of Quality
Quality refers to attributes to estimate the intrinsic characteristics of a product.
Qualities are:
1. Measurable Characteristics
2. Intrinsic Properties

** Types of Quality
Quality is of two types.
1. Quality of design: The degree to which the requirements for design are fulfilled.
2. Quality of conformance: The degree to which a product or service conforms to its requirements.

** Quality Assurance
Quality assurance is the auditing, reporting of functional management. 
The goal of Quality Assurance is to assure the company about software quality.

** Quality Control
It consists of a series of activities throughout the software development process to ensure that the software meets the requirements of the customer.

** Cost Of Quality
Cost of quality is the summarized cost of the whole process. It includes all costs - from requirements gathering to final product, throughout the whole software development process. It includes:
1. Bundle by bundle cost incurred
2. Predict cost by considering future bugs
*** Types of Cost of Quality
Quality costs may be divided into costs associated with prevention, appraisal and failure. 

**** Prevention
This cost includes:
- Formal Technical Review
- Training
- Test Equipments
- Quality Planning
**** Appraisal Cost
This cost includes:
- Gain insight into product condition
- The “first time through” each process
- In-process and inter-process inspection
- Equipment calibration and maintenance
**** Testing
Failure Cost: Failure costs are costs that would disappear if no defects appear before shipping a product to customers. Failure costs may be divided into internal and external failure.

***** Internal Failure Cost
Internal Failure Costs are incurred when we detect a defect in our product prior to shipment. Internal failure costs include:
1. Reward
2. Repair
3. Failure Mode Analysis

***** External Failure Cost
External failure costs are associated with defects found after the product has been shipped to the customer. External failure costs are:
1. Complaint Solution
2. Product return and replacement
3. Helpline support
4. Warranty Work

* Questions
1. What is outsourcing? What is offshore outsouring? What are strategies for successful offshore outsouring?
2. Definition of contingent worker, H1B worker.
3. What are the key ethical issues for organizations?
4. Code of conducts of IT industry
5. Definition of green computing, out sourcing and offshore outsourcing
6. Strategy for successful offshore outsourcing
7. Whistle blowing preparation steps.
8. Definition of intellectual property, copyright, copyright infringement, patent, patent infringement, cross licensing agreement,
9. Eligibility for copyright
10. What are the laws for the proctection of software copyright?
11. Talk about digitial millenium act
12. Describe trade secret.
13. Discuss KEY INTELLECTUAL PROPERTY ISSUES
14. What are the Key Ethical Issues for Organizations?
15. Professionalism, Are IT Workers Professional?
16. Professional Relationships that must be maintained
17. Relationship between IT Workers & Employer
18. Relationship between IT Workers & Clients
19. Business Software Alliance: Stop unauthorized trading & manufacturing of product
20. Professional Code of Conduct
21. IT Professional Organizations
22. Certification: Knowledge, Skill, Abilities
23. Licensing vs Certification

