version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 7000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

    deploy:
      mode: replicated
      replicas: 1

  server:
    image: server
    build: ./server
    # image: user/image-name ## You can also provide an image here
    restart: unless-stopped
    
    deploy:
      mode: replicated
      replicas: 2
  minio-mera:
    image: minio/minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER:rafed
      - MINIO_ROOT_PASSWORD:rafed
    command: server --console-address ":9001" /data

