* Using Familiar Words
1 We must end all deficit financing.
2 We must try to correct this problem by quickening delivery.
3 A flat tax consumes a fixed amount of one’s monetary flow.
4 Business has an excessive influence on governmental operations.
5 It is crucial that consumers be free in determining their preferences.
6 Mr. Sanchez terminated Kevin’s employment as a result of his inadequate performance.
7 We hope that there will be increase in commodity value.
8 Can we find out the types of customers that have a preference to utilize our instant-credit offer?
9 The large part of the business people we consulted envisions signs of improvement from the current siege of economic stagnation.
10 If liquidation becomes inevitable, we shall dispose of these assets first.
11 Recent stock acquisitions have intensified the company’s current financial crisis.
12 Mr. Coward  will be the intermediary in the pending labor–management parley.
13 Ms. Smith’s pecuiliar mannerism supply adequate justification for terminating her employment.
14 The company has enhanced prerequisites for its employment process.
15 The similarity of current forecasts is not undeniable evidence of an impending business acceleration.
16 People’s tendency to consume is insatiable.
17 The company must stop its deficit financing immediately.
18 This old advertisement strategy is ineffective in contemporary business operations.
19 Average Percentage return on common stockholders’ equity reached 23.1 for the year.
20 The company’s retained earnings last year exceeded $2,500,000.

* Using Technical Words Appropriately (LO4)
21

A journal is a collection of articles written by experts. From the list of journals given below, select a paragraph (at least 150 words long) that would be difficult for a student less advanced in the subject than you. Rewrite the paragraph so that this student can understand it easily.

* Selecting Concrete Words (LO5)
22 We have found that men under 21 are best for this work.
23 She usually achieves grades above cgpa 3.81.
24 John lost $20,000 in Las Vegas.
25 If we don’t receive badminton court, net and rackets soon, we will cancel our badminton tournament.
26 5 years ago she made around $20,000.
27 His grade on the aptitude test was 54.
28 Here is a product with 23 markup.
29 The cost of the online subscription was $12.
30 We will need new badminton court, net and rackets soon.
* Confusions
10
